"""Plain-English explanations for calculation-trace steps.

The trace's `input` and `breakdown` fields are machine-friendly JSON; the
summary UI wants prose. This service produces two things per step:

  - `fields`: a list of {label, value} rows for the input/breakdown keys,
    with friendly labels and INR-formatted amounts. Deterministic, no LLM.
  - `plain_text`: a one-paragraph explanation of what the step did and how
    it produced its result. Generated by Gemini when available; falls back
    to the step's existing `human_explanation` when LLM is in stub mode or
    a call fails.

The Gemini path is a single batch call covering every step at once — much
cheaper than per-step round trips, and keeps the explanation set internally
consistent. Output is strict JSON validated against `ExplainResponse`.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from decimal import Decimal
from typing import Any

from app.services.extraction.gemini import get_extractor


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FieldRow:
    label: str          # human label, e.g. "Taxable income"
    value: str          # already-formatted value, e.g. "₹12,00,000.00"
    raw: str            # raw stringified value, e.g. "1200000.00"


@dataclass(frozen=True)
class StepExplanation:
    step: int
    op: str
    plain_text: str
    fields: list[FieldRow]
    source: str         # "gemini" | "deterministic"

    def to_dict(self) -> dict:
        return {
            "step": self.step,
            "op": self.op,
            "plain_text": self.plain_text,
            "fields": [
                {"label": f.label, "value": f.value, "raw": f.raw}
                for f in self.fields
            ],
            "source": self.source,
        }


# ---------------------------------------------------------------------------
# Deterministic label dictionary
# ---------------------------------------------------------------------------

LABELS: dict[str, str] = {
    # context
    "fy": "Financial year",
    "statute": "Statute",
    "regime": "Regime",
    "residency": "Residency status",
    "senior_status": "Age bracket",
    # heads
    "transactions": "Source transactions",
    "head_total": "Head total",
    "salary_after_std_deduction": "Salary after standard deduction",
    "house_property": "House property income",
    "pgbp": "Business / profession income",
    "capital_gains_slab": "Capital gains (slab portion)",
    "other_sources_slab": "Other sources (slab portion)",
    "gti_normal": "Gross total income (slab)",
    "chapter_via": "Chapter VI-A deductions",
    "salary_income": "Salary income",
    "standard_deduction": "Standard deduction (§16(ia))",
    # slab / tax
    "taxable": "Taxable income",
    "taxable_income": "Taxable income",
    "slab_tax": "Slab tax",
    "slab_after_rebate": "Slab tax after rebate",
    "rebate": "§87A rebate",
    "rebate_87a": "§87A rebate",
    "flat_rate_tax": "Flat-rate tax",
    "flat_rate_taxes": "Flat-rate taxes by bucket",
    "surcharge": "Surcharge",
    "cess": "Cess",
    "total_tax": "Total tax payable",
    "tds_paid": "TDS / prepaid taxes",
    "tax_plus_surcharge": "Tax + surcharge (cess base)",
    # rules
    "rule_id": "Rule",
    "rule_version": "Rule version",
    "slab_rule_id": "Slab rule",
    "rebate_rule_id": "Rebate rule",
    "surcharge_rule_id": "Surcharge rule",
    "cess_rule_id": "Cess rule",
    # surcharge marginal-relief inputs
    "total_income": "Total income",
    "total_income_for_surcharge": "Total income for surcharge",
    "marginal_relief_applied": "Marginal relief applied",
    "band_rate": "Surcharge band rate",
    # flat-rate
    "section_ref": "Section",
    "rate": "Rate",
    "amount": "Amount",
    "threshold": "Threshold",
    "bucket": "Flat-rate bucket",
    "buckets": "Flat-rate buckets",
}


def _humanize_key(key: str) -> str:
    if key in LABELS:
        return LABELS[key]
    return key.replace("_", " ").strip().capitalize()


def _inr(value: str | int | float | Decimal) -> str:
    try:
        n = Decimal(str(value))
    except Exception:
        return str(value)
    sign = "-" if n < 0 else ""
    n = abs(n)
    integer, _, frac = f"{n:.2f}".partition(".")
    if len(integer) <= 3:
        grouped = integer
    else:
        head, tail = integer[:-3], integer[-3:]
        parts: list[str] = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        grouped = ",".join(parts) + "," + tail
    return f"{sign}₹{grouped}.{frac}"


def _looks_like_amount(key: str, value: Any) -> bool:
    """Heuristic: render Decimal-shaped strings or numbers as INR for amount-y
    keys. We don't INR-format rate fractions or year strings."""
    if key in {"rate", "fy", "statute", "regime", "residency", "senior_status",
               "section_ref", "rule_id", "rule_version"}:
        return False
    if isinstance(value, (int, float, Decimal)):
        return True
    if isinstance(value, str):
        try:
            Decimal(value)
            # 4-digit integers could be years — treat plain "2024" as not money
            if value.isdigit() and 1900 <= int(value) <= 2100:
                return False
            return "." in value or len(value) > 3
        except Exception:
            return False
    return False


def _render_value(key: str, value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, list):
        # Keep arrays compact — show counts so users aren't drowning in IDs.
        if all(isinstance(x, str) for x in value):
            return f"{len(value)} transaction(s)" if key == "transactions" \
                else ", ".join(value[:5]) + (" …" if len(value) > 5 else "")
        return f"{len(value)} item(s)"
    if isinstance(value, dict):
        return f"{len(value)} field(s)"
    if _looks_like_amount(key, value):
        return _inr(value)
    return str(value)


def _label_and_amount(b: dict, i: int) -> tuple[str, Any]:
    """Pick the right label + amount columns for a breakdown row.

    Different engine steps emit different shapes:

    - Slab band:        {band, rate, amount_in_band, tax}
                        → "₹4L – ₹8L @ 5%" / amount = tax
    - Surcharge bucket: {section, flat_tax, applied_rate, surcharge, capped}
                        → "§111A (capped)" / amount = surcharge
    - Chapter VI-A:     {section, amount, cap, claimed, allowed}
                        → "§80C" / amount = allowed (or amount)
    - Income line:      {description, counterparty, label, category, amount}
                        → employer / bank name / category / amount

    Internal identifiers (txn_id etc.) are intentionally never surfaced.
    """
    keys = set(b.keys())

    # ---- Slab band ---------------------------------------------------------
    if "band" in keys and ("tax" in keys or "amount_in_band" in keys):
        rate_pct = ""
        if "rate" in keys:
            try:
                pct = Decimal(str(b["rate"])) * 100
                rate_pct = f" @ {pct.normalize():f}%".replace(".0%", "%")
            except Exception:
                rate_pct = ""
        label = f"{b['band']}{rate_pct}"
        return label, b.get("tax") if "tax" in keys else b.get("amount_in_band")

    # ---- Surcharge flat-rate bucket ---------------------------------------
    if "section" in keys and "surcharge" in keys:
        capped = bool(b.get("capped"))
        label = f"§{b['section']}" + (" (rate capped)" if capped else "")
        return label, b.get("surcharge")

    # ---- Chapter VI-A allowance ------------------------------------------
    if "section" in keys and ("allowed" in keys or "claimed" in keys):
        return f"§{b['section']}", b.get("allowed", b.get("claimed", b.get("amount")))

    # ---- Generic income line ---------------------------------------------
    label = (
        b.get("description")
        or b.get("counterparty")
        or b.get("label")
        or b.get("name")
        or b.get("category")
        or (f"§{b['section']}" if "section" in keys else None)
        or f"Item {i}"
    )
    return str(label), b.get("amount")


def _to_rows(step_input: Any) -> list[FieldRow]:
    if step_input is None:
        return []
    if isinstance(step_input, dict):
        rows: list[FieldRow] = []
        for k, v in step_input.items():
            rows.append(
                FieldRow(
                    label=_humanize_key(k),
                    value=_render_value(k, v),
                    raw=str(v) if v is not None else "",
                )
            )
        return rows
    # Non-dict input — wrap in a single row.
    return [FieldRow(label="Input", value=_render_value("", step_input), raw=str(step_input))]


# ---------------------------------------------------------------------------
# Gemini batch explanation
# ---------------------------------------------------------------------------

EXPLAIN_SYSTEM = (
    "You are an Indian Income Tax helper. You receive a JSON list of "
    "calculation steps from a deterministic tax engine. For each step, write "
    "ONE short paragraph (2–4 sentences, no markdown, no bullets) explaining "
    "what the step did, what its inputs mean, and how it arrived at its "
    "result. Refer to the relevant section of the Income Tax Act if it is "
    "supplied in the step's section_ref. Use Indian rupee grouping (e.g. "
    "₹12,34,567). Never invent numbers — only restate values that appear in "
    "the step. NEVER include UUIDs, transaction IDs, internal identifiers, "
    "or hex strings in your prose; refer to sources by their employer / "
    "deductor / counterparty name (or generically as 'salary credit', "
    "'interest payment', etc.) instead. Never give tax advice. Return ONLY "
    "JSON matching the schema."
)


# Internal-only fields that must never leak into user-facing prose or
# field rows. Scrubbed from the Gemini prompt and from breakdown labels.
_INTERNAL_FIELDS = frozenset({"txn_id", "tx_id", "transaction_id", "id"})


def _strip_internal(value: Any) -> Any:
    """Recursively strip internal-only keys from a JSON-like structure."""
    if isinstance(value, dict):
        return {k: _strip_internal(v) for k, v in value.items() if k not in _INTERNAL_FIELDS}
    if isinstance(value, list):
        return [_strip_internal(v) for v in value]
    return value


def _build_explain_prompt(steps: list[dict[str, Any]], regime: str, fy: str) -> str:
    payload = {
        "fy": fy,
        "regime": regime,
        "steps": [
            {
                "step": s.get("step"),
                "op": s.get("op"),
                "section_ref": s.get("section_ref"),
                "rule_id": s.get("rule_id"),
                "rule_version": s.get("rule_version"),
                # Strip txn_ids / internal ids from input + breakdown so the
                # model can't echo UUIDs back into its prose.
                "input": _strip_internal(s.get("input")),
                "breakdown": _strip_internal(s.get("breakdown")),
                "result": s.get("result"),
                "human_explanation": s.get("human_explanation"),
            }
            for s in steps
        ],
    }
    schema = {
        "type": "object",
        "properties": {
            "explanations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "step": {"type": "integer"},
                        "plain_text": {"type": "string"},
                    },
                    "required": ["step", "plain_text"],
                },
            }
        },
        "required": ["explanations"],
    }
    return (
        f"```json\n{json.dumps(payload, ensure_ascii=False)}\n```\n\n"
        "Return JSON matching this schema:\n"
        f"```json\n{json.dumps(schema)}\n```"
    )


def _gemini_explanations(
    steps: list[dict[str, Any]], *, regime: str, fy: str
) -> dict[int, str]:
    """Returns {step_number: plain_text}. Empty dict if LLM unavailable / fails."""
    extractor = get_extractor()
    if extractor.is_stub or extractor._model is None:  # noqa: SLF001
        return {}
    try:
        from vertexai.generative_models import GenerationConfig, Part  # type: ignore[import-not-found]
    except ImportError:
        return {}
    try:
        prompt = _build_explain_prompt(steps, regime=regime, fy=fy)
        resp = extractor._model.generate_content(  # noqa: SLF001
            [Part.from_text(EXPLAIN_SYSTEM), Part.from_text(prompt)],
            generation_config=GenerationConfig(
                temperature=0.0,
                top_p=1.0,
                response_mime_type="application/json",
            ),
        )
        # Reuse the extractor's text extractor for finish-reason handling.
        from app.services.extraction.gemini import _extract_text  # type: ignore[attr-defined]
        raw = _extract_text(resp)
        data = json.loads(raw)
    except Exception:
        logger.exception("Trace explainer Gemini call failed; falling back to deterministic.")
        return {}

    out: dict[int, str] = {}
    for item in data.get("explanations", []):
        try:
            out[int(item["step"])] = str(item["plain_text"]).strip()
        except (KeyError, TypeError, ValueError):
            continue
    return out


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def explain_trace(
    trace: dict[str, Any],
    *,
    use_llm: bool = True,
) -> list[StepExplanation]:
    """Produce explanations for every step in a calculation trace.

    `use_llm=False` forces the deterministic path (useful for tests and for
    explicitly opting out of an LLM round-trip on a hot page render).
    """
    steps = trace.get("steps") or []
    regime = str(trace.get("regime", ""))
    fy = str(trace.get("fy", ""))

    llm_map: dict[int, str] = {}
    if use_llm and steps:
        llm_map = _gemini_explanations(steps, regime=regime, fy=fy)

    out: list[StepExplanation] = []
    for s in steps:
        step_num = int(s.get("step", len(out) + 1))
        op = str(s.get("op", "")) or "(unnamed)"
        rows = _to_rows(s.get("input"))

        # Breakdown rows — append after input rows when present. Different
        # engine steps emit different breakdown shapes; pick the right
        # label + amount columns for each so the user sees the band names,
        # employer names, or section refs that actually carry meaning.
        breakdown = s.get("breakdown")
        if isinstance(breakdown, list) and breakdown:
            for i, b in enumerate(breakdown, 1):
                if isinstance(b, dict):
                    label, amt_value = _label_and_amount(b, i)
                    raw = "" if amt_value is None else str(amt_value)
                    value = _inr(amt_value) if amt_value is not None else ""
                    rows.append(FieldRow(label=label, value=value, raw=raw))
                else:
                    rows.append(FieldRow(label=f"Item {i}", value=str(b), raw=str(b)))

        # Always show the step's own result as the final row.
        rows.append(
            FieldRow(
                label="Result",
                value=_inr(s.get("result", "0")),
                raw=str(s.get("result", "0")),
            )
        )

        llm_text = llm_map.get(step_num, "")
        plain = llm_text or str(s.get("human_explanation") or f"{op} step.")
        out.append(
            StepExplanation(
                step=step_num,
                op=op,
                plain_text=plain,
                fields=rows,
                source="gemini" if llm_text else "deterministic",
            )
        )
    return out
