"use client";

import * as React from "react";
import { Card, CardBody } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import type {
  CalculationTraceDTO,
  ExplainStepDTO,
  TraceStepDTO,
} from "@/lib/api/summary";
import { cn } from "@/lib/utils/cn";

function inr(value: string | undefined | null): string {
  if (value == null || value === "") return "—";
  const n = Number(value);
  if (!Number.isFinite(n)) return value;
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
  }).format(n);
}

interface RowProps {
  step: TraceStepDTO;
  explanation: ExplainStepDTO | undefined;
  loading: boolean;
  open: boolean;
  onToggle: () => void;
}

function StepRow({ step, explanation, loading, open, onToggle }: RowProps) {
  return (
    <li className="border-b border-line-subtle last:border-b-0">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-surface-sunken/40"
      >
        <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-surface-sunken text-xs font-semibold text-ink-muted">
          {step.step}
        </span>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium text-ink">{step.op}</span>
            {step.section_ref && (
              <Badge tone="navy" size="sm">
                §{step.section_ref}
              </Badge>
            )}
            {typeof step.rule_version === "number" && (
              <Badge tone="neutral" size="sm">
                rule v{step.rule_version}
              </Badge>
            )}
          </div>
          <p className="mt-0.5 line-clamp-2 text-xs text-ink-muted">
            {explanation?.plain_text ?? step.human_explanation}
          </p>
        </div>
        <span className="shrink-0 text-sm font-semibold tabular-nums text-ink">
          {inr(step.result)}
        </span>
        <span
          aria-hidden
          className={cn(
            "ml-1 inline-block transition-transform",
            open && "rotate-90",
          )}
        >
          ›
        </span>
      </button>
      {open && (
        <div className="border-t border-line-subtle bg-surface-sunken/30 px-4 py-3 text-sm text-ink">
          {loading && !explanation ? (
            <p className="text-ink-muted">Generating explanation…</p>
          ) : (
            <>
              <p className="text-pretty leading-relaxed">
                {explanation?.plain_text ?? step.human_explanation}
              </p>
              {explanation?.source === "gemini" && (
                <p className="mt-1 text-2xs uppercase tracking-wide text-ink-subtle">
                  Generated by Gemini
                </p>
              )}
            </>
          )}

          {explanation && explanation.fields.length > 0 && (
            <dl className="mt-3 divide-y divide-line-subtle rounded-lg border border-line bg-surface-raised">
              {explanation.fields.map((f, i) => (
                <div
                  key={`${f.label}-${i}`}
                  className="flex items-baseline justify-between gap-4 px-3 py-2"
                >
                  <dt className="text-sm text-ink-muted">{f.label}</dt>
                  <dd className="text-sm tabular-nums text-ink">{f.value}</dd>
                </div>
              ))}
            </dl>
          )}
        </div>
      )}
    </li>
  );
}

export function CalculationTraceAccordion({
  trace,
  explanations,
  loading,
}: {
  trace: CalculationTraceDTO;
  explanations: ExplainStepDTO[];
  loading: boolean;
}) {
  const [open, setOpen] = React.useState<Set<number>>(new Set());
  const [allOpen, setAllOpen] = React.useState(false);

  const steps = trace.steps ?? [];
  const byStep = React.useMemo(() => {
    const m = new Map<number, ExplainStepDTO>();
    for (const e of explanations) m.set(e.step, e);
    return m;
  }, [explanations]);

  const toggle = (n: number) => {
    setOpen((prev) => {
      const next = new Set(prev);
      if (next.has(n)) next.delete(n);
      else next.add(n);
      return next;
    });
  };

  const expandAll = () => {
    if (allOpen) {
      setOpen(new Set());
      setAllOpen(false);
    } else {
      setOpen(new Set(steps.map((s) => s.step)));
      setAllOpen(true);
    }
  };

  return (
    <Card>
      <CardBody className="flex flex-col gap-3">
        <div className="flex items-center justify-between gap-3">
          <div>
            <h3 className="font-display text-lg text-ink">Calculation trace</h3>
            <p className="text-sm text-ink-muted">
              Every step the engine took, explained in plain English. Click a
              row to see what went in and how the result was reached.
            </p>
          </div>
          {steps.length > 0 && (
            <button
              type="button"
              onClick={expandAll}
              className="shrink-0 text-sm text-navy underline-offset-2 hover:underline"
            >
              {allOpen ? "Collapse all" : "Expand all"}
            </button>
          )}
        </div>
        {steps.length === 0 ? (
          <p className="text-sm text-ink-subtle">No trace recorded yet.</p>
        ) : (
          <ul className="overflow-hidden rounded-lg border border-line bg-surface-raised">
            {steps.map((s) => (
              <StepRow
                key={s.step}
                step={s}
                explanation={byStep.get(s.step)}
                loading={loading}
                open={open.has(s.step)}
                onToggle={() => toggle(s.step)}
              />
            ))}
          </ul>
        )}
        {trace.rule_versions && Object.keys(trace.rule_versions).length > 0 && (
          <details className="mt-1 text-xs text-ink-muted">
            <summary className="cursor-pointer select-none">
              Rule versions pinned to this trace
            </summary>
            <ul className="mt-2 divide-y divide-line-subtle rounded border border-line bg-surface-sunken">
              {Object.entries(trace.rule_versions).map(([k, v]) => (
                <li
                  key={k}
                  className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-0.5 px-3 py-1.5"
                >
                  <span className="text-ink-muted">{k}</span>
                  <span className="flex items-baseline gap-2">
                    <span className="tabular-nums text-ink">v{v.version}</span>
                    <span className="text-ink-subtle">{v.statute}</span>
                    <span className="text-ink-subtle" title={v.source}>
                      {v.source.includes(":") ? v.source.split(":")[0] : v.source}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </details>
        )}
      </CardBody>
    </Card>
  );
}
